#!/bin/bash

command_exists()
{
	command -v "$1" >/dev/null 2>&1	
}

# PreReq Installs
if command_exists brew; then
	echo "Homebrew Is Installed"
else
	echo "Installing Homebrew"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Installs Using Home Brew
# brew install git || exit 1
# brew install pyenv || exit 1
# brew install tmux || exit 1
# brew install neovim || exit 1
# brew install bat || exit 1
# brew install fzf || exit 1

# Installs using Bash
# sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
#        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'


# Symlink dotfiles
